### PR TITLE
Postgres EventStreamRepository

### PR DESCRIPTION
**Pull request by marconi**
NOTE: I wasn't sure how exactly is integration and correlation events different from the main `events` and/or how it is being used so I created separate tables for each. Let me know if this isn't right and I'd be happy to refactor it. :)

### CODE REVIEW

**Comment by andrewwebber** [comment]
It would be great to have a documentation markdown file indicating how to run this test after starting a local postgres docker container. If I can start a postgres docker container and run the test, and it passes, then i can accept the merge request. 

i will also try to setup a test script that runs all the providers as part of my merge request quality process.

Hope thats ok

**Comment by marconi** [comment]
@andrewwebber yep that's fine, added `README.md` file. Cheers!

**Comment by andrewwebber** [comment]
Thanks for the readme. I am trying to execute the tests.
I have started postgres SQL with the following command
```
sudo docker run --name postgres -e POSTGRES_PASSWORD=admin --net="host" -v $PWD/postgres:/scripts -d postgres
```
Then i try to create a database
```
sudo docker exec -it postgres sh -c "cd /scripts/ && createdb cqrs_postgres_test"
```

but it fails with the following message.
```
createdb: could not connect to database template1: FATAL:  role "root" does not exist
```

I appologize, I am not a postgres expect. My goal is to have these providers executed during the drone build process, if your wondering :)

**Comment by marconi** [comment]
@andrewwebber ah no worries, sec let me update it with a complete Docker instructions as well.

**Comment by marconi** [comment]
@andrewwebber updated with details instruction using postgres:9.4.5 container. Also would be nice to get your thoughts on what's the difference between integration, correlation and just normal events? thanks! :)

**Comment by andrewwebber** [comment]
Merged. 

> Also would be nice to get your thoughts on what's the difference between integration, correlation and just normal events

Would you be able to discuss this in a separate issue so it's tracked? Thanks

**Comment by marconi** [comment]
@andrewwebber sure

**Pull request merged**
